/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0/samples
 */

plugins {
    kotlin("jvm") version "1.4.31"
    `java-gradle-plugin`
    `maven-publish`
    id("com.gradle.plugin-publish") version "0.14.0"
}

group = "at.stnwtr"
version = "1.0.0"

repositories {
    mavenCentral()
}

gradlePlugin {
    plugins {
        create(rootProject.name) {
            id = "$group.${rootProject.name}"
            implementationClass = "$group.${rootProject.name.replace('-', '_')}.SecretsPlugin"
            displayName = "Gradle Secrets Plugin"
            description = "A small plugin which loads an additional properties file for secret values."
        }
    }
}

pluginBundle {
    website = "https://github.com/stnwtr/gradle-secrets-plugin"
    vcsUrl = "https://github.com/stnwtr/gradle-secrets-plugin.git"
    tags = listOf("secrets", "value", "secret", "credentials", "file", "hidden", "key", "password", "token")
}
