/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.0/samples
 */

plugins {
    kotlin("jvm") version "1.4.31"
    `java-gradle-plugin`
    `maven-publish`
}

group = "at.stnwtr"
version = "1.0.0"

repositories {
    mavenCentral()
}

gradlePlugin {
    plugins {
        create(rootProject.name) {
            id = "$group.${rootProject.name}"
            implementationClass = "$group.${rootProject.name.replace('-', '_')}.SecretsPlugin"
        }
    }
}
